### PR TITLE
Use FSharpType and FSharpValue instead of direct use of reflection

### PR DESCRIPTION
**Pull request by Arshia001**
OK, I **just** learned about `FSharpType` and `FSharpValue`. I updated the remoting code in the dotnet client to work with `FSharpType`. Functionally, the code does the exact same thing. It's just more readable now. Sorry about this, really. 🙇🏻‍♂️

### CODE REVIEW

**Comment by Zaid-Ajaj** [comment]
> It's just more readable now. Sorry about this, really. 🙇🏻‍♂️

No worries at all @Arshia001 :smile: I noticed it in the original PR but didn't mind it since it worked perfectly. This makes it more readable indeed, thanks a lot :pray:

**Comment by Arshia001** [comment]
Next time, tell me before I embarrass myself please 😅

**Comment by Zaid-Ajaj** [comment]
Will do :wink:

**Comment by Arshia001** [comment]
@Zaid-Ajaj Say, remember how I said this code was exactly equivalent to the one before? Turns out it's not.

See, F# generates a class constructor for each record. Parameters to that constructor are named similarly to the record's fields, except that they're converted to snakeCase if the field name is PascalCase. This means that the previous code generates a snakeCased version of the route: `MyApi/someHandler` instead of `MyApi/SomeHandler`.

Since Giraffe is normally case-sensitive and FSLint forces record field names to be PascalCase, this makes the previous code essentially unusable. This PR already fixes the error, and it's already been merged. Just one package update and all would be in order.

Again, I'm really sorry about all of this.

**Comment by Zaid-Ajaj** [comment]
Hi @Arshia001, don't worry about it, I just published version 3.10 of Fable.Remoting.DotnetClient that uses this implementation and it should be available in a moment :smile: please give it a try and let me know if I broke something in the process

**Comment by Arshia001** [comment]
Everything seems to be in order. Thanks :)

**Pull request merged**
