### PR TITLE
Internalize TypeShape, take #2

### PR DESCRIPTION
**Pull request by kerams**

### CODE REVIEW

**Comment by kerams** [comment]
Any ideas about excluding the two files from the Nuget package?

**Comment by Zaid-Ajaj** [comment]
> Any ideas about excluding the two files from the Nuget package?

You can conditionally `Compile` the files based on the `FABLE_COMPILER` I believe so that Fable won't compile them but I guess compiler directives like `#if !FABLE_COMPILER` in the files themselves are better because then the tests would catch any funky business that is otherwise not visible until someone compiles the nuget and it breaks

**Comment by kerams** [comment]
Added. The files will still be shipped, but I guess it's no biggie.

**Comment by Zaid-Ajaj** [comment]
A fresh batch is published to include this fix, let's see if the SAFE template issue with 32-bit apps is fixed 🤞

**Pull request merged**
