### PR TITLE
WIP: Tiny fixes and Update to netcoreapp3.0

### PR DESCRIPTION
**Pull request by tforkmann**
I ran all tests and they were all successful. If you need me to revert some stuff let me know.

Best,

Tim

### CODE REVIEW

**Comment by forki** [comment]
Can you please squash the commits?

**Comment by tforkmann** [comment]
Not sure what’s wrong with the Travis build

**Comment by Zaid-Ajaj** [comment]
Heyy Tim, thanks a lot for the upgrade and the cleanups :heart: don't worry about Travis, it's just acting weird again because of the long build times (can be sped up by telling it not to install mono) if appveyor is happy then that it fine by me

There are a couple of changes I would like to put in 
 - removing ionides symbol cache because that is just an IDE thing
 - deleting the conditional code in Remoting.Json instead of commmenting it out

I will merge now and fix these things myself, thanks again for the PR

**Comment by Zaid-Ajaj** [comment]
Published all packages with the netcoreapp3.0 target framework and bumped up all of their minor version by 1
Should be available soon on nuget :smile:

**Pull request merged**
