### PR TITLE
End to end testing: turning existing integration tests into unit tests

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
Testing the whole stack with selenium. Just run:
```
./build.sh IntegrationTests
```
Will be added to the CI pipeline soon.

Needs more polishing when it comes to the results, you will only see something like this:
```
Passed: 54
Failed: 0
```

### CODE REVIEW

**Comment by Nhowka** [comment]
Looks like it failed in something other than the tests... The output seems ok
```
Passed: 54
Failed: 0
```

**Comment by Zaid-Ajaj** [comment]
Yeah it seems that selenium sends a request to the firefox driver everytime you ask it for the text content, it threw an exception because I asked for the value after closing the driver, I think it is fixed now

**Comment by Nhowka** [comment]
Now it should be easier to detect those pesky bugs that keeping creeping into the releases! 😄

**Comment by Zaid-Ajaj** [comment]
Awwh yeahh, it is working!!! 



No more bugs hopefully :heart:

**Pull request merged**
