### PR TITLE
Implement MsgPack serialization in Fable

### PR DESCRIPTION
**Pull request by kerams**
@Shmew, had to slightly change the API since Fable won't let me just do `GetType` on an object. When calling `Write.object` from Fable, you also need to provide the type of the object being serialized.

### CODE REVIEW

**Comment by Zaid-Ajaj** [comment]
Hi @kerams, will you let me know when this is ready to review/merge? :smile:

**Comment by kerams** [comment]
Should be good as is.

**Comment by Zaid-Ajaj** [comment]
:fire: Published :fire: like always, awesome stuff @kerams thanks a lot 🙇 :heart:

- `Fable.Remoting.MsgPack` updated version `1.1.0 -> 1.2.0`
- `Fable.Remoting.Client` updated version `6.2.0 -> 6.3.0` 

cc @Shmew maybe now #159 becomes doable

**Comment by Shmew** [comment]
This is exciting! Thanks @kerams!

**Pull request merged**
