### PR TITLE
Work around stackalloc codegen bug

### PR DESCRIPTION
**Pull request by kerams**
https://github.com/Zaid-Ajaj/Fable.Remoting/issues/304, https://github.com/dotnet/fsharp/issues/13447

### CODE REVIEW

**Comment by sWW26** [comment]
Any chance this could get this merged & released?

**Comment by kerams** [comment]
@Zaid-Ajaj, v1.17 with this fix sets an upper constraint on FSharp.Core for some reason. Any idea how this happened?

image

**Comment by Zaid-Ajaj** [comment]
@kerams I think latest paket is more strict when you say `nuget FSharp.Core ~> 4.7.2` it means `>= 4.7.2 && < 4.8` but previously it didn't do that. Now I've changed the requirement to `nuget FSharp.Core >= 4.7.2` with strategy `lowest_matching: true` and published a new batch so it should be alright I think 🤞 

In any case, huge thanks for the fix 🙏  I would not have known how and where to start fixing this 😅 

@sWW26 A new batch of remoting packages have been published 🚀 , when upgrading, please make sure to update both client _and_ server when doing so.

**Comment by sWW26** [comment]
That's great. Thanks both!

**Pull request merged**
