### PR TITLE
Fix withCredentials = false not working

### PR DESCRIPTION
**Pull request by KittisakT**
Related issue #217

### CODE REVIEW

**Comment by Zaid-Ajaj** [comment]
Thanks a lot @KittisakT I don't how I missed that one 😓 just merged and published Fable.Remoting.Client v7.5 that includes the fix 🚀 should be on nuget in a moment 😄

**Comment by kerams** [comment]
`WithCredentials` is initialized to `false` so this also changes the current default behavior.

**Comment by Zaid-Ajaj** [comment]
Should we make initialization optional until the user provides a value? i.e. use `bool option` in the config? According to [this](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials), the default is `false`

**Comment by kerams** [comment]
That could still break something after upgrading for consumers that rely on the current ("incorrect/buggy") behavior. Then again, there's no way around it if we're going to follow the guidance you posted, which I'd be in favor of.

So in the end maybe just keep it as it is? Just felt like pointing out the potential problem 😄.

**Comment by Zaid-Ajaj** [comment]
> Then again, there's no way around it if we're going to follow the guidance you posted, which I'd be in favor of.

I was thinking the same, we can't do much about it, will just keep it as is

**Pull request merged**
