### PR TITLE
Fix regression introduced with case label rename.

### PR DESCRIPTION
**Pull request by janno-p**

### CODE REVIEW

**Comment by Nhowka** [comment]
Wonder how CI was green before that... Thank you for fixing it!

**Comment by Zaid-Ajaj** [comment]
> Wonder how CI was green before that

Because I should have written some tests/docs for them but didn't have the time to :(

**Comment by Nhowka** [comment]
Don't worry, these new features were the most niche we ever had, but I feel like stuff like that should don't even compile. You are doing a great job on all your projects! 😉

**Comment by Zaid-Ajaj** [comment]
Thank you @Nhowka  :kissing_heart: appreciate it!  

>  I feel like stuff like that should don't even compile

I think it is because the unknown case was considered a variable name that it compiled correctly

@janno-p Client package 2.5.1 is published, should be available soon from Nuget

**Comment by janno-p** [comment]
Exactly, it actually produced some annoying warnings in webpack console: first about unconventional label (with uppercase first letter), and since it matched every case, there were also two warnings about patterns wich will be never matched.

Otherwise, great, will update soon.

**Pull request merged**
