### PR TITLE
Saturn

### PR DESCRIPTION
**Pull request by Nhowka**
Adapter for use with [Saturn](https://github.com/SaturnFramework/Saturn).

### CODE REVIEW

**Comment by Zaid-Ajaj** [comment]
Wow, this is awesome! :heart: the code looks good, I will merge right away. We still need to add the integration tests though, but that can be done later.

**Comment by Zaid-Ajaj** [comment]
The code can be simplified by referencing the already implemented methods from Fable.Remoting.Giraffe. I will take a look

**Comment by Nhowka** [comment]
Good idea! The code barely changed so that should be easier to maintain!

**Comment by Krzysztof-Cieslak** [comment]
Oh wow ❤️

**Pull request merged**
