### PR TITLE
Allow to pass custom HttpClient to DotnetClient proxy.

### PR DESCRIPTION
**Pull request by irium**
This allows using Fable.Remoting with ASPNET.Core's TestServer and TestClient:
```
    let server = new TestServer(WebHostBuilder().UseStartup<Startup>()
    let client = server.CreateClient()
    let builder = ...
    let proxy = Proxy.custom<'T> builder client
```

### CODE REVIEW

**Comment by Zaid-Ajaj** [comment]
Nice addition, thanks a lot! already pushed and published in the next version 1.2.0 :smile:

**Comment by irium** [comment]
Thank you too! Because I really need this and currently using home-grown version of it. But it's always better to have it "out of the box" :)

**Comment by Zaid-Ajaj** [comment]
It is refreshing to see someone *actually* using this thing :smile:

**Comment by Zaid-Ajaj** [comment]
File upload/download could be added to the library but I would rather limit the scope of problems the library tries to solve. If you can handle file/upload with a couple lines of code and you happen to need that only once or twice, then a library feature is a bit overkill for that.

**Comment by irium** [comment]
Agree. But some sort of recipe in the docs wouldn't hurt? ;)

I'm still curious about how it could be done : pass it as byte array? But because of JSON-encoding built-in it is wasteful in terms of traffic :(

**Comment by Zaid-Ajaj** [comment]
@irium Indeed passing it as a byte array is a big waste! it doesn't make sense from the proxy's point of view because we are only using `application/json` as the MIME-type for data exchange, so to make it work we would use a special request with `multipart/form-data` for handling files. But again, doing this with "raw" http without abstractions is the way to go IMO. 

BTW added the docs to your PR [here](https://zaid-ajaj.github.io/Fable.Remoting/src/dotnet-http-client.html), let me know if you want add/change anything :smile:

**Comment by irium** [comment]
Docs seems good to me.

**Pull request merged**
